//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecCore.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_units
    {
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public string graphsymbol_rus { get; set; }
        public string graphsymbol_int { get; set; }
        public string codesymbol_rus { get; set; }
        public string codesymbol_int { get; set; }
        public string p_quantity { get; set; }
    }
}
