//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public album()
        {
            this.tblNodeDepths = new HashSet<tblNodeDepth>();
            this.tblNodesContents = new HashSet<tblNodesContent>();
            this.listalbs = new HashSet<listalb>();
        }
    
        public int id_album { get; set; }
        public string name_alb { get; set; }
        public string description_alb { get; set; }
        public Nullable<bool> in_design { get; set; }
        public string compr_name { get; set; }
        public string created_alb_orig_login { get; set; }
        public string file_path { get; set; }
        public Nullable<bool> is_end_prod_alb { get; set; }
        public Nullable<int> id_fact { get; set; }
    
        public virtual factory factory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNodeDepth> tblNodeDepths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNodesContent> tblNodesContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listalb> listalbs { get; set; }
    }
}
