//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class allLayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public allLayer()
        {
            this.objecttypes = new HashSet<objecttype>();
        }
    
        public int ID_Layer { get; set; }
        public string LayerName { get; set; }
        public Nullable<bool> IsOff { get; set; }
        public Nullable<bool> IsFrozen { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public short Color { get; set; }
        public string LineType { get; set; }
        public int LineWeight { get; set; }
        public bool IsPlottable { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objecttype> objecttypes { get; set; }
    }
}
