//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLPLAN_mods_to_NPCon
    {
        public int id_AP_mods { get; set; }
        public string Марка { get; set; }
        public string модификатор { get; set; }
        public Nullable<bool> modif_exist { get; set; }
        public Nullable<int> id_ap { get; set; }
        public string RMark { get; set; }
        public Nullable<int> id_modif { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public Nullable<int> Item_modification_id { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string Responsible_person { get; set; }
        public Nullable<System.DateTime> moved_to_Prod_mod { get; set; }
        public string comment { get; set; }
        public Nullable<int> t_a { get; set; }
        public Nullable<int> id_object { get; set; }
    }
}
