//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLPLAN_to_NPCon
    {
        public int id_ap { get; set; }
        public string Тип { get; set; }
        public string НаименованиеNPCon { get; set; }
        public string RightMark { get; set; }
        public Nullable<int> ГабаритнаяТолщина { get; set; }
        public Nullable<int> Толщина { get; set; }
        public Nullable<int> Длина { get; set; }
        public Nullable<int> ГабаритнаяДлина { get; set; }
        public Nullable<int> Высота { get; set; }
        public Nullable<int> ГабаритнаяВысота { get; set; }
        public Nullable<decimal> Площадь { get; set; }
        public Nullable<decimal> Объем { get; set; }
        public Nullable<decimal> Вес { get; set; }
        public Nullable<int> КоличествоКанатов { get; set; }
        public Nullable<int> ВысотаБезСтупенькиРеновация { get; set; }
        public Nullable<decimal> ОбъемВнутреннегоСлоя { get; set; }
        public Nullable<decimal> ОбъемНаружногоСлоя { get; set; }
        public Nullable<decimal> ОбъемУтеплителя { get; set; }
        public Nullable<int> ТолщинаВнутреннегоСлоя { get; set; }
        public Nullable<int> ТолщинаНаружногоСлоя { get; set; }
        public Nullable<int> ТолщинаУтеплителя { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string Responsible_person { get; set; }
        public Nullable<System.DateTime> moved_to_NPCon { get; set; }
        public Nullable<int> id_object { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public Nullable<int> id_end_prod_ver { get; set; }
        public string Item_group_MDM { get; set; }
        public string comment { get; set; }
        public Nullable<int> t_a { get; set; }
    }
}
