//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLPLAN_KB_differ
    {
        public string НаименованиеNPCon { get; set; }
        public string Марка { get; set; }
        public Nullable<int> id_object { get; set; }
        public Nullable<int> id_endprod_ver { get; set; }
        public Nullable<int> ОсновнаяДлина_АП { get; set; }
        public Nullable<int> ОсновнаяДлина_КБ { get; set; }
        public string ОДлина_ош { get; set; }
        public Nullable<int> ГабаритнаяДлина_АП { get; set; }
        public Nullable<int> ГабаритнаяДлина_КБ { get; set; }
        public string ГДлина_ош { get; set; }
        public Nullable<int> ОсновнаяВысота_АП { get; set; }
        public Nullable<int> ОсновнаяВысота_КБ { get; set; }
        public string ОВысота_ош { get; set; }
        public Nullable<int> ГабаритнаяВысота_АП { get; set; }
        public Nullable<int> ГабаритнаяВысота_КБ { get; set; }
        public string ГВысота_ош { get; set; }
        public Nullable<int> ОсновнаяТолщина_АП { get; set; }
        public Nullable<int> ОсновнаяТолщина_КБ { get; set; }
        public string ОТолщина_ош { get; set; }
        public Nullable<int> ГабаратинаяТолщина_АП { get; set; }
        public Nullable<int> ГабаритнаяТолщина_КБ { get; set; }
        public string ГТолщина_ош { get; set; }
        public Nullable<decimal> Площадь_АП { get; set; }
        public Nullable<decimal> Площадь_КБ { get; set; }
        public string Площадь_ош { get; set; }
        public Nullable<decimal> Объем_АП { get; set; }
        public Nullable<decimal> Объем_КБ { get; set; }
        public string Объем_ош { get; set; }
        public Nullable<decimal> Вес_АП { get; set; }
        public Nullable<decimal> Вес_КБ { get; set; }
        public string Вес_ош { get; set; }
        public Nullable<int> КоличествоКанатов_АП { get; set; }
        public string КоличествоКанатов_КБ { get; set; }
        public string Канаты_ош { get; set; }
        public Nullable<decimal> ОбъемВнутреннегоСлоя_АП { get; set; }
        public Nullable<decimal> ОбъемВнутреннегоСлоя_КБ { get; set; }
        public string ОбъемВнутреннегоСлоя_ош { get; set; }
        public Nullable<decimal> ОбъемНаружногоСлоя_АП { get; set; }
        public Nullable<decimal> ОбъемНаружногоСлоя_КБ { get; set; }
        public string ОбъемНаружногоСлоя_ош { get; set; }
        public Nullable<decimal> ОбъемУтеплителя_АП { get; set; }
        public Nullable<decimal> ОбъемУтеплителя_КБ { get; set; }
        public string ОбъемУтеплителя_ош { get; set; }
        public Nullable<int> ТолщинаВнутреннегоСлоя_АП { get; set; }
        public Nullable<decimal> ТолщинаВнутреннегоСлоя_КБ { get; set; }
        public string ТолщинаВнутреннегоСлоя_ош { get; set; }
        public Nullable<int> ТолщинаНаружногоСлоя_АП { get; set; }
        public Nullable<decimal> ТолщинаНаружногоСлоя_КБ { get; set; }
        public string ТолщинаНаружногоСлоя_ош { get; set; }
        public Nullable<int> ТолщинаУтеплителя_АП { get; set; }
        public Nullable<decimal> ТолщинаУтеплителя_КБ { get; set; }
        public string ТолщинаУтеплителя_ош { get; set; }
        public string Есть_несоответствия { get; set; }
        public string Несоответствия_АП_КБ { get; set; }
        public Nullable<int> Not_AP_max_ver { get; set; }
    }
}
