//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class angle
    {
        public int id_object_angle { get; set; }
        public byte largewidth { get; set; }
        public byte smallwidth { get; set; }
        public decimal thickness { get; set; }
        public string precision { get; set; }
    
        public virtual raw raw { get; set; }
    }
}
