//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class arm
    {
        public int id_object_arm { get; set; }
        public byte diam { get; set; }
        public string method { get; set; }
        public Nullable<short> strength { get; set; }
        public string armproperty { get; set; }
    
        public virtual raw raw { get; set; }
    }
}
