//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspa_entity
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<int> gid { get; set; }
        public string description { get; set; }
        public string uuid { get; set; }
    }
}
