//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly_structure
    {
        public System.Guid UID_Assembly { get; set; }
        public Nullable<System.Guid> UID_Part { get; set; }
        public Nullable<System.Guid> UID_Assembly_Part { get; set; }
        public string Matrix_Assembly { get; set; }
        public int Number_Assembly_Part { get; set; }
    
        public virtual Assembly Assembly { get; set; }
        public virtual Assembly Assembly1 { get; set; }
        public virtual Part Part { get; set; }
    }
}
