//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_changes_delete
    {
        public string ServerName { get; set; }
        public string DB_Name { get; set; }
        public string ViewName { get; set; }
        public string type { get; set; }
        public System.DateTime create_date { get; set; }
        public string View_script { get; set; }
        public System.DateTime modify_date { get; set; }
    }
}
