//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1stg_modificators
    {
        public int id { get; set; }
        public int Item_modification_id { get; set; }
        public string Item_modification_code { get; set; }
        public string NPCon_mod { get; set; }
        public string Robot_mod { get; set; }
        public string Description { get; set; }
    }
}
