//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmd_user_lisp
    {
        public int id_userlogin { get; set; }
        public int id_lisp { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual cmd_lisp cmd_lisp { get; set; }
        public virtual cmd_userlogins cmd_userlogins { get; set; }
    }
}
