//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmd_log
    {
        public string UserLogin { get; set; }
        public string UserDomain { get; set; }
        public System.DateTime RecDateTime { get; set; }
        public string NameCmd { get; set; }
        public string NameFile { get; set; }
        public string PC_name { get; set; }
    }
}
