//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coloristic
    {
        public int id_coloristics { get; set; }
        public string project_name { get; set; }
        public string section { get; set; }
        public string floor { get; set; }
        public string mark { get; set; }
        public string coloristics_index { get; set; }
        public string insert_point { get; set; }
        public string rotation { get; set; }
        public string points { get; set; }
        public string json { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string resp_person { get; set; }
    }
}
