//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class end_prod_ver_RawConsist
    {
        public int id_endprod_ver { get; set; }
        public int id_object_raw { get; set; }
        public decimal raw_count { get; set; }
        public System.DateTime created_at { get; set; }
        public string creator_username { get; set; }
        public string btn_groupname { get; set; }
    
        public virtual end_product_version end_product_version { get; set; }
        public virtual raw raw { get; set; }
    }
}
