//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public floor()
        {
            this.project_specific = new HashSet<project_specific>();
        }
    
        public System.Guid UID_floors { get; set; }
        public System.Guid UID_sections { get; set; }
        public string Name_floors { get; set; }
        public System.Guid UID_FILE { get; set; }
        public bool Deleted_Floors { get; set; }
        public System.DateTime Data_Time { get; set; }
        public string Login { get; set; }
    
        public virtual section section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_specific> project_specific { get; set; }
    }
}
