//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fstn_element
    {
        public int id_object_felem { get; set; }
        public int id_name_felem { get; set; }
        public string mark_felem { get; set; }
        public string addition { get; set; }
    
        public virtual fstn_name fstn_name { get; set; }
        public virtual raw raw { get; set; }
    }
}
