//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KZI
    {
        public System.Guid UID_KZI_Name { get; set; }
        public System.Guid UID_Assembly { get; set; }
        public int Version_KZI { get; set; }
        public Nullable<int> WorkFileId { get; set; }
        public bool Deleted_KZI { get; set; }
        public string C2d_Plan_KZI { get; set; }
        public string C2d_Fasade_KZI { get; set; }
        public System.DateTime Data_Time { get; set; }
        public string Login { get; set; }
    
        public virtual work_file work_file { get; set; }
        public virtual Assembly Assembly { get; set; }
        public virtual KZI_Name KZI_Name { get; set; }
    }
}
