//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class last_changes_mark_ver
    {
        public int id_change { get; set; }
        public int id { get; set; }
        public bool isVerID { get; set; }
        public string creator { get; set; }
        public System.DateTime created_at { get; set; }
        public string tbl_name { get; set; }
        public bool isUpdated { get; set; }
    }
}
