//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Line()
        {
            this.end_product_version = new HashSet<end_product_version>();
            this.factory_lines = new HashSet<factory_lines>();
            this.rep_prod = new HashSet<rep_prod>();
        }
    
        public string C_Вид_формования { get; set; }
        public string C_Распалубка { get; set; }
        public string C_Вид_армирования { get; set; }
        public string C_Класс_стали { get; set; }
        public string C_Тип_бетона { get; set; }
        public string C_CAD_данные { get; set; }
        public int id_line { get; set; }
        public int id_formEquip { get; set; }
        public System.Guid forming_lifting_guid { get; set; }
        public int id_arm_type { get; set; }
        public int id_class_of_steel { get; set; }
        public int id_type_of_concr { get; set; }
        public bool CAD { get; set; }
        public bool actual { get; set; }
        public string line_name { get; set; }
        public string UID_1c { get; set; }
        public string short_name { get; set; }
        public byte[] row_ver { get; set; }
    
        public virtual arm_type arm_type { get; set; }
        public virtual concrType concrType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<end_product_version> end_product_version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factory_lines> factory_lines { get; set; }
        public virtual formingEquip formingEquip { get; set; }
        public virtual steelClass steelClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rep_prod> rep_prod { get; set; }
    }
}
