//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaded_Marks_from_1C_ver2
    {
        public decimal ID_MDM { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> OverallOfLength { get; set; }
        public Nullable<decimal> OverallOfHeight { get; set; }
        public Nullable<decimal> OverAllHeight { get; set; }
        public Nullable<decimal> VolumeOfInnerLayer { get; set; }
        public Nullable<decimal> VolumeOfOuterLayer { get; set; }
        public Nullable<decimal> VolumeOfInsulation { get; set; }
        public Nullable<decimal> ThicknessOfInnerLayer { get; set; }
        public Nullable<decimal> ThicknessOfOuterLayer { get; set; }
        public Nullable<decimal> ThicknessOfInsulation { get; set; }
        public Nullable<decimal> NumberOfRopes { get; set; }
    }
}
