//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAD_T_16_082020_v2
    {
        public string mark { get; set; }
        public Nullable<int> id_obj { get; set; }
        public string objType { get; set; }
        public string UserName { get; set; }
        public int mainLen { get; set; }
        public int mainHeight { get; set; }
        public int mainThick { get; set; }
        public int overLen { get; set; }
        public int overHeight { get; set; }
        public int overThick { get; set; }
        public decimal C63 { get; set; }
        public decimal C62 { get; set; }
        public decimal C64 { get; set; }
        public decimal VGazoB { get; set; }
        public decimal C61 { get; set; }
        public bool C25 { get; set; }
        public bool C40 { get; set; }
        public bool C48 { get; set; }
        public int C66 { get; set; }
        public int C67 { get; set; }
        public int C68 { get; set; }
        public bool C34 { get; set; }
        public decimal Vmark { get; set; }
    }
}
