//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks_and_modifications_MDMdeleted
    {
        public Nullable<int> Item_construction_modification_id { get; set; }
        public Nullable<int> Item_construction_id { get; set; }
        public Nullable<int> Item_modification_id { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int t_a { get; set; }
    }
}
