//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks_and_modifications_to_1C
    {
        public string marks { get; set; }
        public string modification { get; set; }
        public Nullable<int> ID_marks { get; set; }
        public Nullable<int> ID_groups { get; set; }
        public Nullable<int> ID_modificators { get; set; }
        public Nullable<int> ID_modificators_gr { get; set; }
        public System.Guid UUID { get; set; }
        public Nullable<int> t_a { get; set; }
        public string Responsible_person { get; set; }
        public string type_of_insert { get; set; }
        public Nullable<int> id_object_nm { get; set; }
        public Nullable<int> id_modif_nm { get; set; }
    }
}
