//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks_and_modifications_nm
    {
        public string Mark { get; set; }
        public string RMark { get; set; }
        public string К { get; set; }
        public string ПВ { get; set; }
        public string З { get; set; }
        public string ЗФ { get; set; }
        public string ЗП { get; set; }
        public string ТЛ { get; set; }
        public string ТП { get; set; }
        public string УТ { get; set; }
        public string ПО { get; set; }
        public string ПБ { get; set; }
        public string ПД { get; set; }
        public string ПТ { get; set; }
        public string СП120 { get; set; }
        public string СЛ120 { get; set; }
        public string СП150 { get; set; }
        public string СЛ150 { get; set; }
        public string СП245 { get; set; }
        public string СЛ245 { get; set; }
        public string СП275 { get; set; }
        public string СЛ275 { get; set; }
        public string СВ { get; set; }
        public string С { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public Nullable<int> id_aperture { get; set; }
        public string aperture_geometry { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> moved_to_mdm { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
        public string comment { get; set; }
        public Nullable<int> t_a { get; set; }
        public int actual { get; set; }
        public string Responsible_person { get; set; }
        public string type_of_insert { get; set; }
        public string С200 { get; set; }
        public string С240 { get; set; }
        public string Г { get; set; }
    }
}
