//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks_and_modifications
    {
        public string Status { get; set; }
        public string by_modificators { get; set; }
        public string by_apertures { get; set; }
        public string necessity { get; set; }
        public string RMark { get; set; }
        public string console { get; set; }
        public string Tooth { get; set; }
        public string Insulation { get; set; }
        public string loop_release { get; set; }
        public string backs { get; set; }
        public string Author { get; set; }
        public string type_of_aperture { get; set; }
        public string brace { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public Nullable<int> id_aperture { get; set; }
        public string aperture_geometry { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> moved_to_mdm { get; set; }
        public Nullable<int> update { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
        public string comment { get; set; }
        public Nullable<int> t_a { get; set; }
        public int actual { get; set; }
        public string Responsible_person { get; set; }
        public string type_of_insert { get; set; }
    }
}
