//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Item_modification
    {
        public int Item_modification_id { get; set; }
        public Nullable<int> Item_modification_id_access { get; set; }
        public string Item_modification_code { get; set; }
        public Nullable<int> Item_modification_type_id { get; set; }
        public Nullable<int> Side_id { get; set; }
        public Nullable<int> Item_modification_point { get; set; }
        public Nullable<int> Item_modification_measure { get; set; }
        public string Description { get; set; }
        public byte[] version { get; set; }
    }
}
