//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Item_construction
    {
        public int Item_construction_id { get; set; }
        public Nullable<int> Item_construction_id_access { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public int Item_group_id { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Thickness { get; set; }
        public Nullable<short> Formwork { get; set; }
        public string Electrics { get; set; }
        public Nullable<int> Steps { get; set; }
        public Nullable<int> First_step { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<float> Volume { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
        public byte[] version { get; set; }
        public Nullable<float> Surface_area { get; set; }
        public Nullable<short> Thickness_size { get; set; }
    }
}
