//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Layer_documents_state_actual_t
    {
        public string Documents { get; set; }
        public string Layer { get; set; }
        public string Layer_description { get; set; }
        public bool Visiblity { get; set; }
        public bool Template { get; set; }
    }
}
