//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Item_construction_modification
    {
        public int Item_construction_modification_id { get; set; }
        public int Item_construction_id { get; set; }
        public int Item_modification_id { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
        public byte[] version { get; set; }
    }
}
