//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Forming_type_v
    {
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> forming_dimension_guid { get; set; }
        public Nullable<System.Guid> forming_lifting_guid { get; set; }
    }
}
