//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Item_modification_type_t
    {
        public int id_modif_Type { get; set; }
        public Nullable<int> Item_modification_type_id { get; set; }
        public Nullable<int> Item_modification_type_rank { get; set; }
        public string Item_modification_type { get; set; }
    }
}
