//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Item_colour
    {
        public int Item_colour_id { get; set; }
        public Nullable<int> Item_colour_id_access { get; set; }
        public string Item_colour { get; set; }
        public string Item_colour_hash { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
