//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdm_Item_modification_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mdm_Item_modification_t()
        {
            this.modification_parameter = new HashSet<modification_parameter>();
            this.modificationType4object_type = new HashSet<modificationType4object_type>();
        }
    
        public int id_modif { get; set; }
        public Nullable<int> Item_modification_id { get; set; }
        public Nullable<int> Item_modification_id_access { get; set; }
        public string Item_modification_code { get; set; }
        public Nullable<int> Item_modification_type_id { get; set; }
        public Nullable<int> Side_id { get; set; }
        public Nullable<int> Item_modification_point { get; set; }
        public Nullable<int> Item_modification_measure { get; set; }
        public string Description { get; set; }
        public Nullable<int> type_input { get; set; }
        public Nullable<int> proof_KB { get; set; }
        public bool is_single { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modification_parameter> modification_parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modificationType4object_type> modificationType4object_type { get; set; }
    }
}
