//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mod_param_value_pool_07042020
    {
        public int id_mod_param_value_pool { get; set; }
        public int id_modif { get; set; }
        public int id_param { get; set; }
        public int height { get; set; }
        public int width { get; set; }
        public Nullable<int> thickness { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string created_original_login { get; set; }
    }
}
