//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class modification_parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modification_parameter()
        {
            this.mod_param_value_pool = new HashSet<mod_param_value_pool>();
            this.product_modification = new HashSet<product_modification>();
        }
    
        public int id_modif { get; set; }
        public int id_param { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string created_original_login { get; set; }
        public string name_in_DWG { get; set; }
    
        public virtual mdm_Item_modification_t mdm_Item_modification_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mod_param_value_pool> mod_param_value_pool { get; set; }
        public virtual parameter parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_modification> product_modification { get; set; }
    }
}
