//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomenclature_current
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nomenclature_current()
        {
            this.project_specific_OLD = new HashSet<project_specific_OLD>();
        }
    
        public System.Guid UID { get; set; }
        public System.Guid UID_Geometry { get; set; }
        public Nullable<System.Guid> UID_Parameters { get; set; }
        public string Name { get; set; }
        public string Geometry_Compare { get; set; }
        public string Parameter_Compare { get; set; }
    
        public virtual Geometry Geometry { get; set; }
        public virtual Parameter1 Parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_specific_OLD> project_specific_OLD { get; set; }
    }
}
