//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomenclature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nomenclature()
        {
            this.project_specific = new HashSet<project_specific>();
        }
    
        public System.Guid UID_nomenclature { get; set; }
        public string Nomenclature_type { get; set; }
        public System.Guid UID_KZI_Name { get; set; }
        public Nullable<System.Guid> UID_Color { get; set; }
        public System.DateTime Data_Time { get; set; }
        public string Login { get; set; }
    
        public virtual color color { get; set; }
        public virtual KZI_Name KZI_Name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_specific> project_specific { get; set; }
    }
}
