//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.Objects1 = new HashSet<Object>();
            this.projects = new HashSet<project>();
        }
    
        public int Object_id { get; set; }
        public Nullable<int> Object_id_access { get; set; }
        public Nullable<int> Object_id_parent { get; set; }
        public Nullable<int> Object_type_id { get; set; }
        public string Cadaster_number { get; set; }
        public string Object_name { get; set; }
        public Nullable<int> Object_number { get; set; }
        public string Object_number_add { get; set; }
        public Nullable<int> Project_type_id { get; set; }
        public Nullable<int> Usage_mos_id { get; set; }
        public Nullable<int> Address_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Building_part_id { get; set; }
        public Nullable<int> Construction_type_id { get; set; }
        public Nullable<short> Floors { get; set; }
        public Nullable<int> Froor_type_id { get; set; }
        public Nullable<int> Area_id { get; set; }
        public bool Is_building { get; set; }
        public bool Is_floor { get; set; }
        public bool Is_technical { get; set; }
        public Nullable<System.Guid> Object_IDP_TUS_SID { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.Guid guid { get; set; }
        public byte[] version { get; set; }
        public string Object_IDP_MDS_Guid1C { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object> Objects1 { get; set; }
        public virtual Object Object1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
    }
}
