//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class objectconsist
    {
        public int id_object_cons { get; set; }
        public int id_subobject { get; set; }
        public int count { get; set; }
        public decimal blanklen { get; set; }
        public string len_units { get; set; }
        public Nullable<int> id_mark4subelem { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public int objectcons_ver { get; set; }
        public byte[] row_ver { get; set; }
    
        public virtual objectmark objectmark { get; set; }
        public virtual p_units p_units { get; set; }
        public virtual p_object p_object { get; set; }
        public virtual p_object p_object1 { get; set; }
    }
}
