//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class objecttype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public objecttype()
        {
            this.modificationType4object_type = new HashSet<modificationType4object_type>();
            this.objectprefixes = new HashSet<objectprefix>();
            this.p_object = new HashSet<p_object>();
            this.objecttype1 = new HashSet<objecttype>();
            this.objecttypes = new HashSet<objecttype>();
            this.allLayers = new HashSet<allLayer>();
        }
    
        public int id_objecttype { get; set; }
        public bool isproduct { get; set; }
        public string objecttypename { get; set; }
        public string typeShortName { get; set; }
        public Nullable<bool> isendproduct { get; set; }
        public Nullable<int> id_type4mark { get; set; }
        public System.Guid objtypguid { get; set; }
        public string tbl_unit { get; set; }
    
        public virtual mark_type mark_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modificationType4object_type> modificationType4object_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objectprefix> objectprefixes { get; set; }
        public virtual p_units p_units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_object> p_object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objecttype> objecttype1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objecttype> objecttypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<allLayer> allLayers { get; set; }
    }
}
