//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_hdpe
    {
        public int id_object_hdpe { get; set; }
        public byte diam_hdpe { get; set; }
        public string d_pref { get; set; }
        public string diam_hdpe_unit { get; set; }
    
        public virtual p_units p_units { get; set; }
        public virtual raw raw { get; set; }
    }
}
