//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_object_Dev
    {
        public Nullable<int> id_normdoc_pobj { get; set; }
        public int id_object { get; set; }
        public int id_objecttype_pobj { get; set; }
        public string unitsguid_pobj { get; set; }
        public bool isagreed { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> agreedate { get; set; }
        public string created_original_login { get; set; }
        public string created_comp_name { get; set; }
        public string created_username { get; set; }
        public string agree_original_login { get; set; }
        public string agree_comp_name { get; set; }
        public string agree_username { get; set; }
        public string unicname { get; set; }
        public string unicname_trim { get; set; }
        public Nullable<bool> actual { get; set; }
        public bool DeletionMark { get; set; }
        public bool Load_1C { get; set; }
    }
}
