//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_object()
        {
            this.objectconsists = new HashSet<objectconsist>();
            this.objectconsists1 = new HashSet<objectconsist>();
            this.RCP_nomenclature = new HashSet<RCP_nomenclature>();
        }
    
        public Nullable<int> id_normdoc_pobj { get; set; }
        public int id_object { get; set; }
        public int id_objecttype_pobj { get; set; }
        public string unitsguid_pobj { get; set; }
        public bool isagreed { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> agreedate { get; set; }
        public string created_original_login { get; set; }
        public string created_comp_name { get; set; }
        public string created_username { get; set; }
        public string agree_original_login { get; set; }
        public string agree_comp_name { get; set; }
        public string agree_username { get; set; }
        public string unicname { get; set; }
        public string unicname_trim { get; set; }
        public Nullable<bool> actual { get; set; }
        public bool DeletionMark { get; set; }
        public bool Load_1C { get; set; }
        public byte[] row_ver { get; set; }
    
        public virtual normdoc normdoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objectconsist> objectconsists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objectconsist> objectconsists1 { get; set; }
        public virtual objecttype objecttype { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCP_nomenclature> RCP_nomenclature { get; set; }
        public virtual raw raw { get; set; }
        public virtual p_units p_units { get; set; }
    }
}
