//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_PEfilm
    {
        public int id_object_PEfilm { get; set; }
        public decimal thick_PEfilm { get; set; }
        public string thick_PEfilm_unit { get; set; }
    
        public virtual p_units p_units { get; set; }
        public virtual raw raw { get; set; }
    }
}
