//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class params_loaded_from_1c_old
    {
        public decimal ID_MDM { get; set; }
        public string Name { get; set; }
        public string NameN { get; set; }
        public string Name_with_param { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Square_of_ObjGeom { get; set; }
        public Nullable<int> Item_modification_id { get; set; }
        public string type_of_panel { get; set; }
    }
}
