//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_OS_26_02_2021
    {
        public int id_object_prod { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public string listnum_prod { get; set; }
        public Nullable<int> id_album_prod { get; set; }
        public string blkname { get; set; }
        public string nrm_unicname_trim { get; set; }
        public Nullable<int> prodlength { get; set; }
        public Nullable<int> prodheight { get; set; }
        public string file_path { get; set; }
        public byte[] prodpreview { get; set; }
        public Nullable<int> prod_thickness { get; set; }
        public Nullable<bool> outdoor { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<decimal> prod_weight { get; set; }
        public Nullable<int> height_full { get; set; }
        public Nullable<int> id_work_file { get; set; }
        public Nullable<int> length_full { get; set; }
        public Nullable<int> thickness_full { get; set; }
        public Nullable<int> rotate_layers { get; set; }
        public Nullable<bool> buying_part { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<bool> renovation { get; set; }
        public Nullable<bool> copy_mdm { get; set; }
        public Nullable<System.DateTime> chkd_URK { get; set; }
        public Nullable<System.DateTime> chkd_KTD { get; set; }
        public Nullable<bool> archive { get; set; }
        public Nullable<decimal> product_area_1С { get; set; }
        public Nullable<decimal> Weight_1С { get; set; }
        public bool copy_1C { get; set; }
    }
}
