//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_specific_OLD
    {
        public System.Guid UID_floor { get; set; }
        public System.Guid UID_nomenclature { get; set; }
        public Nullable<System.Guid> UID_Parameters { get; set; }
        public string matrix_Insertion { get; set; }
        public string Parameters_Insertion { get; set; }
    
        public virtual floors_OLD floors_OLD { get; set; }
        public virtual nomenclature_current nomenclature_current { get; set; }
        public virtual Parameter1 Parameter { get; set; }
    }
}
