//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_specific
    {
        public System.Guid UID_floors { get; set; }
        public System.Guid UID_nomenclature { get; set; }
        public string matrix_Insertion { get; set; }
        public System.DateTime Data_Time { get; set; }
        public string Login { get; set; }
        public string JSON_Project_Specific { get; set; }
    
        public virtual floor floor { get; set; }
        public virtual nomenclature nomenclature { get; set; }
    }
}
