//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCP_nomenclature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RCP_nomenclature()
        {
            this.RCP_consistancy = new HashSet<RCP_consistancy>();
        }
    
        public int id_RCP { get; set; }
        public int id_obj { get; set; }
        public int id_col_index { get; set; }
    
        public virtual p_object p_object { get; set; }
        public virtual Colour_index Colour_index { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCP_consistancy> RCP_consistancy { get; set; }
    }
}
