//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCP_consistancy
    {
        public int id_RCP_cons { get; set; }
        public int id_RCP { get; set; }
        public int id_col_art { get; set; }
        public Nullable<int> consumption { get; set; }
        public Nullable<decimal> square_cons { get; set; }
    
        public virtual Colour_article Colour_article { get; set; }
        public virtual RCP_nomenclature RCP_nomenclature { get; set; }
    }
}
