//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rds_ins
    {
        public int id_rds { get; set; }
        public Nullable<int> id_object { get; set; }
        public string mark { get; set; }
        public int thickness { get; set; }
        public string height_width { get; set; }
        public Nullable<int> id_modif { get; set; }
        public Nullable<int> mod_num { get; set; }
        public Nullable<int> mod_num_plus { get; set; }
    }
}
