//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_prod
    {
        public int id { get; set; }
        public Nullable<int> prod_type { get; set; }
        public Nullable<int> prod_sort { get; set; }
        public string prod_name { get; set; }
        public string cur_user { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> Project_id { get; set; }
        public Nullable<int> Korpus_id { get; set; }
        public Nullable<int> series { get; set; }
        public Nullable<int> factory { get; set; }
        public Nullable<int> tehnology { get; set; }
        public string description { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> x1 { get; set; }
        public Nullable<int> x2 { get; set; }
        public Nullable<int> y1 { get; set; }
        public Nullable<int> y2 { get; set; }
        public Nullable<int> z1 { get; set; }
        public Nullable<int> z2 { get; set; }
        public Nullable<int> id_fact { get; set; }
        public Nullable<int> id_line { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
