//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class some_new_mods
    {
        public string modificator { get; set; }
        public string mark { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string GUID { get; set; }
        public string MDM_mod { get; set; }
        public string Robot_mod { get; set; }
    }
}
