//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class stage_1_2_mods
    {
        public int id_object_prod { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public string unicname_trim { get; set; }
        public Nullable<int> Item_modification_ID { get; set; }
        public string Модификатор { get; set; }
        public string Параметр { get; set; }
        public string Значение { get; set; }
    }
}
