//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mark_code_type_C1P
    {
        public bool Item_group_usage { get; set; }
        public string Item_group { get; set; }
        public string Item_group_long { get; set; }
        public System.Guid guid { get; set; }
        public int Item_group_id { get; set; }
        public int Item_group_long_id { get; set; }
    }
}
