//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AspecificErrorLog
    {
        public int id_err { get; set; }
        public string e_Message { get; set; }
        public string e_StackTrace { get; set; }
        public string e_InnerException { get; set; }
        public string e_Source { get; set; }
        public string e_TargetSite { get; set; }
        public Nullable<System.DateTime> log_Date { get; set; }
        public string created_original_login { get; set; }
        public string dwg_name { get; set; }
        public Nullable<bool> in_work { get; set; }
        public Nullable<bool> solved { get; set; }
    }
}
