//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserActivityStat
    {
        public System.Guid id_log { get; set; }
        public string UserLogin { get; set; }
        public string CompName { get; set; }
        public System.DateTime StartACAD { get; set; }
        public System.DateTime EndACAD { get; set; }
        public int FullTimeWork { get; set; }
    }
}
