//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserLispErrorLog
    {
        public System.Guid Guid_UserErrorLog { get; set; }
        public string LoginName { get; set; }
        public string UserDomain { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CommandName { get; set; }
        public string DrawingName { get; set; }
        public string ComputerName { get; set; }
    }
}
