//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModificators_OLD
    {
        public System.Guid Id { get; set; }
        public int ProjectId { get; set; }
        public string IfcGuid { get; set; }
        public string SystemTag { get; set; }
        public string Tag { get; set; }
        public string UnitTag { get; set; }
        public string FacadeType { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Thickness { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> Mass { get; set; }
        public string MaterialId { get; set; }
        public string MaterialName { get; set; }
        public string MaterialQuantity { get; set; }
        public Nullable<int> ElementType { get; set; }
        public Nullable<double> Volume { get; set; }
        public string СoloristicsTagList { get; set; }
        public string EndTypeList { get; set; }
        public string JointTypeList { get; set; }
        public string AdvanceTag { get; set; }
        public string ConstructionType { get; set; }
        public string Hole { get; set; }
        public string MarkPrefix { get; set; }
        public string MarkSubPrefix { get; set; }
        public Nullable<int> SeriesId { get; set; }
        public string ParseString { get; set; }
        public string JSON { get; set; }
        public Nullable<bool> IsProduct { get; set; }
        public string SAT { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
    
        public virtual tblProject tblProject { get; set; }
        public virtual tblSery tblSery { get; set; }
    }
}
