//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNodesContent
    {
        public System.Guid uid { get; set; }
        public int AlbumId { get; set; }
        public string NodeName { get; set; }
        public string NodeSheet { get; set; }
        public string Handles { get; set; }
        public double MinX { get; set; }
        public double MinY { get; set; }
        public double MaxX { get; set; }
        public double MaxY { get; set; }
        public double BaseScale { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateLogin { get; set; }
        public bool Actual { get; set; }
    
        public virtual album album { get; set; }
    }
}
