//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_View_Арматура
    {
        public int ID { get; set; }
        public string тип { get; set; }
        public string ед_изм__объекта { get; set; }
        public string марка { get; set; }
        public decimal вес_за_1_ед_изм_изделия { get; set; }
        public string ед_изм__веса { get; set; }
        public bool согласовано { get; set; }
        public Nullable<System.DateTime> дата_согласования { get; set; }
        public System.DateTime создано { get; set; }
        public string кто_создал { get; set; }
        public string тип_норм_док_ { get; set; }
        public string имя_документа { get; set; }
        public byte диаметр { get; set; }
        public string метод { get; set; }
        public Nullable<short> прочность { get; set; }
        public string свойство { get; set; }
    }
}
