//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_view_idSubObj4objType
    {
        public int id_objecttype { get; set; }
        public string objecttypename { get; set; }
        public int id_subobject { get; set; }
        public int id_object_cons { get; set; }
        public string Expr1 { get; set; }
    }
}
