//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_NP_PO
    {
        public int id_obj { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public string Name { get; set; }
        public int id_modif { get; set; }
        public string value { get; set; }
        public Nullable<int> cnt { get; set; }
    }
}
