//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_Модификаторы_используемые
    {
        public string Item_modification_code { get; set; }
        public string Description { get; set; }
        public int id_modif { get; set; }
        public Nullable<int> Item_modification_id { get; set; }
        public Nullable<int> type_input { get; set; }
        public bool is_single { get; set; }
        public Nullable<int> proof_KB { get; set; }
    }
}
