//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporary3
    {
        public int max_id_endprod_ver { get; set; }
        public int id_object { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Thickness { get; set; }
        public string Item_group { get; set; }
        public string poisk1 { get; set; }
        public string poisk2 { get; set; }
        public Nullable<int> C1_point_coord { get; set; }
        public Nullable<int> C2point_coord { get; set; }
        public Nullable<int> C2_1_dif { get; set; }
        public string Len_from_mark { get; set; }
        public string find_thick { get; set; }
        public string Height_from_mark { get; set; }
        public Nullable<int> Thknss_from_mark { get; set; }
    }
}
