//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_load_thickness
    {
        public int id { get; set; }
        public string pref { get; set; }
        public Nullable<int> t66 { get; set; }
        public Nullable<int> t67 { get; set; }
        public Nullable<int> t68 { get; set; }
    }
}
