//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_View_1_Rec
    {
        public int id_object_cons { get; set; }
        public int id_subobject { get; set; }
        public int count { get; set; }
        public int blanklen { get; set; }
        public string len_units { get; set; }
        public Nullable<int> id_mark4subelem { get; set; }
    }
}
