//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporary4
    {
        public Nullable<int> max_id_endprod_ver { get; set; }
        public int id_object_prod { get; set; }
        public Nullable<int> id_objecttype_pobj { get; set; }
        public Nullable<bool> isendproduct { get; set; }
        public Nullable<bool> isproduct { get; set; }
        public string blkname { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Thickness { get; set; }
        public string mark { get; set; }
        public Nullable<int> Len_from_mark { get; set; }
        public Nullable<int> Height_from_mark { get; set; }
        public Nullable<int> Thknss_from_mark { get; set; }
    }
}
