//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_OC_ALL
    {
        public int ID { get; set; }
        public string тип { get; set; }
        public string тип_норм_док_ { get; set; }
        public string имя_норм__док { get; set; }
        public string ед_изм_ { get; set; }
        public string марка { get; set; }
        public string имя_блока { get; set; }
        public int id_суб_объекта { get; set; }
        public string тип_суб_об_ { get; set; }
        public string марка_суб_объекта { get; set; }
        public int кол_во_суб_об_ { get; set; }
        public decimal длина_суб_об_ { get; set; }
        public Nullable<decimal> вес_за_1_ед_изм__суб_об_ { get; set; }
    }
}
