//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_View_Утеплитель
    {
        public int ID { get; set; }
        public string марка { get; set; }
        public string имя_блока { get; set; }
        public Nullable<int> длина { get; set; }
        public Nullable<int> высота { get; set; }
        public Nullable<int> толщина { get; set; }
        public string тип_объекта { get; set; }
        public bool продукт { get; set; }
        public Nullable<bool> конечный_продукт { get; set; }
    }
}
