//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_View_Row_Test
    {
        public int ID_сырья { get; set; }
        public decimal Вес_за_1м_ { get; set; }
        public string Сырьё { get; set; }
        public string Тип_норм_документа { get; set; }
        public string C__ГОСТа { get; set; }
        public string Описани_ГОСТа { get; set; }
        public string ед_измерения { get; set; }
        public string ед_изм_веса { get; set; }
        public string unicname { get; set; }
        public byte largewidth { get; set; }
        public byte smallwidth { get; set; }
        public byte thickness { get; set; }
        public string precision { get; set; }
    }
}
