//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporary8
    {
        public string Марка { get; set; }
        public Nullable<int> Длина { get; set; }
        public Nullable<int> Длина_из_марки { get; set; }
        public string Ошибка_длины { get; set; }
        public Nullable<int> Высота { get; set; }
        public Nullable<int> Высота_из_марки { get; set; }
        public string Ошибка_высоты { get; set; }
        public Nullable<int> Толщина { get; set; }
        public Nullable<int> Толщина_из_марки { get; set; }
        public string Ошибка_толщины { get; set; }
        public string Создатель_последней_версии_марки { get; set; }
        public string Анализ { get; set; }
    }
}
