//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_del_KTD__ASpecific_
    {
        public string Марка { get; set; }
        public string Модификатор_KTD__ASpecific_ { get; set; }
        public Nullable<int> id_object_nm { get; set; }
        public Nullable<int> id_modif_nm { get; set; }
        public Nullable<int> ID_MDM { get; set; }
        public Nullable<int> Item_modification_ID { get; set; }
    }
}
