//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Error_PVL_07
    {
        public string mark { get; set; }
        public int id_obj { get; set; }
        public int objtype { get; set; }
        public int OverLen { get; set; }
        public int OverHeight { get; set; }
        public int OverT { get; set; }
    }
}
