//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Error_V_07
    {
        public string mark { get; set; }
        public int idobj { get; set; }
        public int objType { get; set; }
        public decimal V_mark { get; set; }
        public decimal V_Out { get; set; }
    }
}
