//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Error_LHW_07
    {
        public string mark { get; set; }
        public int id_obj { get; set; }
        public int MainLen { get; set; }
        public int MainHeight { get; set; }
        public int MainW { get; set; }
        public int overLen { get; set; }
        public int overH { get; set; }
        public int overW { get; set; }
    }
}
