//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_npcontmp_tbl_mark_parsing
    {
        public int id { get; set; }
        public string GUID { get; set; }
        public string mark { get; set; }
        public string parsing { get; set; }
        public string blk_name { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string created_original_login { get; set; }
    }
}
