//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_DoubleModif_all
    {
        public int id { get; set; }
        public Nullable<int> countOfModif { get; set; }
        public int id_object_prod { get; set; }
        public int id_modif { get; set; }
        public byte modif_number { get; set; }
    }
}
