//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tube
    {
        public int id_object_tube { get; set; }
        public decimal diam { get; set; }
        public decimal thickness { get; set; }
        public int id_normdoc_tube { get; set; }
    
        public virtual raw raw { get; set; }
    }
}
