//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_factory_lines
    {
        public Nullable<int> id_линии { get; set; }
        public string Название_завода { get; set; }
        public string Префикс_завода { get; set; }
        public string Видформования { get; set; }
        public string ВидКантования { get; set; }
        public string ВидАрмирования { get; set; }
        public string МаркаСтали { get; set; }
        public string КлассБетона { get; set; }
        public string CAD_Данные { get; set; }
        public Nullable<bool> Актуальность_линии { get; set; }
        public bool Актуальность_линии_на_заводе { get; set; }
        public string Полное_наименование_линии { get; set; }
    }
}
