//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ind_rods
    {
        public int id_object { get; set; }
        public string ОС { get; set; }
        public string ОС_блок_на_чертеже { get; set; }
        public Nullable<bool> актуальность_ОС { get; set; }
        public string Составляющее { get; set; }
        public Nullable<int> Кол_во_составляющих { get; set; }
        public Nullable<decimal> Длина_составляющего { get; set; }
        public string unitname { get; set; }
        public Nullable<byte> diam { get; set; }
        public string method { get; set; }
        public Nullable<short> strength { get; set; }
        public string armproperty { get; set; }
        public string Марка_стали { get; set; }
        public int Фиксация { get; set; }
        public Nullable<int> id_типа_ОС { get; set; }
        public string Тип_ОС { get; set; }
        public Nullable<long> row_ver { get; set; }
        public string ИД_ед_изм { get; set; }
        public Nullable<int> id_steelClass { get; set; }
        public string Имя_по_регламенту { get; set; }
    }
}
