//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_MARKS_MODS_to_delete_from_MDM
    {
        public string M_M_MDM1 { get; set; }
        public Nullable<int> Item_con_id { get; set; }
        public int Item_mod_id { get; set; }
        public Nullable<int> ID_mods_group { get; set; }
        public string Rmark_name { get; set; }
        public string mod_name { get; set; }
    }
}
