//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_WINDOWS
    {
        public string Марка { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public Nullable<int> Код_проема { get; set; }
        public string Тип_проема { get; set; }
        public string Ширина { get; set; }
        public string Длина { get; set; }
    }
}
