//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ktd_heater_3d
    {
        public int ID { get; set; }
        public string blkname { get; set; }
        public Nullable<int> prodlength { get; set; }
        public Nullable<int> prodheight { get; set; }
        public Nullable<int> prod_thickness { get; set; }
        public string objecttypename { get; set; }
    }
}
