//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_idObType4MarkPref
    {
        public System.Guid guid { get; set; }
        public string objecttypename { get; set; }
        public int id_objecttype { get; set; }
        public string Item_group { get; set; }
        public string tbl_unit { get; set; }
        public int Item_group_id { get; set; }
    }
}
