//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Shelf_mark_MaxID
    {
        public Nullable<int> id_max { get; set; }
        public string right_mark { get; set; }
        public string blk_handle { get; set; }
        public string UUID_file { get; set; }
        public string mark_from_dwg { get; set; }
        public string PanType { get; set; }
        public int shelf { get; set; }
    }
}
