//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_msaspa_taskmanager_items_work
    {
        public int id { get; set; }
        public string name { get; set; }
        public string factory { get; set; }
        public string forming_type { get; set; }
        public string revision { get; set; }
        public string state { get; set; }
        public Nullable<int> id_obj { get; set; }
        public Nullable<int> id_endprod_ver { get; set; }
        public Nullable<int> id_line { get; set; }
    }
}
