//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ItemConstModif
    {
        public Nullable<int> id_object_prod { get; set; }
        public int id_objecttype { get; set; }
        public int id_modif { get; set; }
        public int Item_modification_id { get; set; }
        public int Item_construction_modification_id { get; set; }
        public int Item_construction_id { get; set; }
        public System.Guid guid { get; set; }
        public System.DateTime updated_at { get; set; }
        public string Item_modification_code { get; set; }
        public string Description { get; set; }
        public string Item_modification_type { get; set; }
    }
}
