//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_concreteInObjects
    {
        public int id_object_concr { get; set; }
        public int id_class { get; set; }
        public int id_binder { get; set; }
        public int id_frost { get; set; }
        public int id_waterres { get; set; }
        public int id_composition { get; set; }
        public decimal object_count { get; set; }
        public int id_endprod_ver { get; set; }
        public string object_count_unit { get; set; }
        public string unicname { get; set; }
    }
}
