//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_end_prod_ver_RawConsist_SumKg
    {
        public int id_endprod_ver { get; set; }
        public int id_object_raw { get; set; }
        public Nullable<decimal> raw_countSum { get; set; }
        public Nullable<System.DateTime> maxdatecreate { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> AllMass { get; set; }
    }
}
