//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cmd_group_lisp
    {
        public int id_lisp { get; set; }
        public string lisp { get; set; }
        public int id_group { get; set; }
        public string group_name { get; set; }
        public string description { get; set; }
    }
}
