//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_endproduct_cut
    {
        public Nullable<int> id_normdoc_pobj { get; set; }
        public Nullable<int> id_object { get; set; }
        public string unicname { get; set; }
        public string name_alb { get; set; }
        public Nullable<int> id_object_prod { get; set; }
        public string blkname { get; set; }
        public Nullable<int> prodlength { get; set; }
        public Nullable<int> prodheight { get; set; }
        public Nullable<int> id_objecttype { get; set; }
        public string unicname_trim { get; set; }
        public Nullable<int> prod_thickness { get; set; }
        public int id_endprod_ver { get; set; }
        public int modification_num { get; set; }
        public System.DateTime created_at { get; set; }
        public string creator_username { get; set; }
        public int id_eprod_album { get; set; }
        public Nullable<System.Guid> itm_conFrm_guid { get; set; }
        public string status_name { get; set; }
        public Nullable<int> length_full { get; set; }
        public Nullable<int> height_full { get; set; }
        public Nullable<int> thickness_full { get; set; }
        public Nullable<decimal> end_prod_weight { get; set; }
        public Nullable<decimal> end_prod_volume { get; set; }
        public string frm_dimension { get; set; }
        public string frm_lifting { get; set; }
        public Nullable<System.Guid> formin_type_guid { get; set; }
        public Nullable<decimal> end_prod_area { get; set; }
        public Nullable<bool> renovation { get; set; }
        public Nullable<int> id_rep_pod { get; set; }
        public string prod_name { get; set; }
        public Nullable<int> id_line { get; set; }
        public Nullable<int> id_tskmng_item { get; set; }
    }
}
