//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_end_prod_ver_allMass
    {
        public int id_endprod_ver { get; set; }
        public Nullable<System.DateTime> maxDate { get; set; }
        public Nullable<decimal> verMass { get; set; }
    }
}
