//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_modifType_4objType
    {
        public int id_objecttype { get; set; }
        public int id_modif { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string created_original_login { get; set; }
        public string Item_modification_code { get; set; }
        public string Description { get; set; }
        public string objecttypename { get; set; }
        public Nullable<int> type_input { get; set; }
        public Nullable<int> proof_KB { get; set; }
    }
}
