//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_objconsist
    {
        public int id_object_cons { get; set; }
        public int id_objTypeMainObj { get; set; }
        public string objTypeNameMainObj { get; set; }
        public string unicnameMainObj { get; set; }
        public bool isproductMainObj { get; set; }
        public Nullable<bool> isendproductMainObj { get; set; }
        public int id_subobject { get; set; }
        public int id_objecttype { get; set; }
        public string objecttypename { get; set; }
        public string unicname { get; set; }
        public bool isproduct { get; set; }
        public Nullable<bool> isendproduct { get; set; }
        public int count { get; set; }
        public string len_units { get; set; }
        public string unicname_trim { get; set; }
        public string unicTrim_MainObj { get; set; }
        public Nullable<bool> actual { get; set; }
        public Nullable<bool> actualMainObj { get; set; }
        public Nullable<int> id_mark4subelem { get; set; }
        public Nullable<int> id_type4mark { get; set; }
        public Nullable<int> id_type4markMainObj { get; set; }
        public decimal blanklen { get; set; }
    }
}
