//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_person_alias_4_login_users
    {
        public int id_user { get; set; }
        public string user_login { get; set; }
        public int id_domain { get; set; }
        public string domain { get; set; }
        public int id_lisp { get; set; }
        public int id_alias { get; set; }
        public string alias { get; set; }
    }
}
