//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_coloristics
    {
        public string code { get; set; }
        public string Name_sections { get; set; }
        public string Name_floors { get; set; }
        public string Name_KZI { get; set; }
        public string Name_Color { get; set; }
        public string matrix_Insertion { get; set; }
        public string C2d_Fasade_KZI { get; set; }
        public string JSON_Project_Specific { get; set; }
        public System.DateTime Data_Time { get; set; }
        public string Login { get; set; }
    }
}
