//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_TEMP_PR_last_UUID
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public string P_Mark { get; set; }
        public string RightMark { get; set; }
        public string p_t { get; set; }
        public string p_h { get; set; }
        public string p_b { get; set; }
        public string UUID_file { get; set; }
    }
}
