//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Item_construction_modification_list_C1P
    {
        public string КЖИ { get; set; }
        public string Модификация { get; set; }
        public string Тип_модификации { get; set; }
        public string Сторона { get; set; }
        public Nullable<int> Размер_модификации { get; set; }
        public string Классификатор_сокращений { get; set; }
        public string Схема_работы { get; set; }
        public string Количество_слоев { get; set; }
        public Nullable<int> Количество_сторон_опирания { get; set; }
        public int Идентификатор_КЖИ { get; set; }
        public Nullable<int> Идентификатор_модификации_КЖИ { get; set; }
        public Nullable<int> Идентификатор_модификации { get; set; }
        public Nullable<int> Идентификатор_типа_модификации { get; set; }
        public Nullable<int> Порядок { get; set; }
    }
}
