//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_end_prod_consist_Mark_2ASPA
    {
        public string objecttypename { get; set; }
        public string unicname_trim { get; set; }
        public int id_object { get; set; }
        public int id_endprod_ver { get; set; }
        public decimal object_count { get; set; }
        public string blkname { get; set; }
        public string MarkName { get; set; }
        public string name_alb { get; set; }
        public string file_path { get; set; }
    }
}
