//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_fact_lines
    {
        public int id_fact { get; set; }
        public string f_name { get; set; }
        public string f_prefix { get; set; }
        public int id_line { get; set; }
        public int id_formEquip { get; set; }
        public string formEquip_Name { get; set; }
        public System.Guid forming_lifting_guid { get; set; }
        public string forming_lifting { get; set; }
        public int id_arm_type { get; set; }
        public string arm_typeName { get; set; }
        public int id_class_of_steel { get; set; }
        public string steel_class { get; set; }
        public int id_type_of_concr { get; set; }
        public string cncr_type { get; set; }
        public bool CAD { get; set; }
        public bool actual { get; set; }
        public int id_fact_line { get; set; }
        public bool fact_lines_actual { get; set; }
        public string line_name { get; set; }
    }
}
