//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewNodesContent
    {
        public int id_album { get; set; }
        public string name_alb { get; set; }
        public string description_alb { get; set; }
        public string file_path { get; set; }
        public System.Guid uid { get; set; }
        public string NodeName { get; set; }
        public string NodeSheet { get; set; }
        public string Handles { get; set; }
        public double MinX { get; set; }
        public double MinY { get; set; }
        public double MaxX { get; set; }
        public double MaxY { get; set; }
        public double scale { get; set; }
    }
}
