//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ItmConsId_by_IdNPCon
    {
        public string Hand_mark_no_colour { get; set; }
        public int Item_construction_id { get; set; }
        public int id_endprod_ver { get; set; }
        public string unicname_trim { get; set; }
        public int id_object { get; set; }
    }
}
