//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_NPCon_mods_1
    {
        public int id_object_prod { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public string unicname_trim { get; set; }
        public Nullable<int> Item_modification_ID { get; set; }
        public Nullable<int> id_modif { get; set; }
        public string Модификатор1 { get; set; }
        public string Параметр1 { get; set; }
        public string Значение1 { get; set; }
    }
}
