//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_РазницаПараметров5
    {
        public string ФИО { get; set; }
        public string Марка { get; set; }
        public Nullable<int> Вес_1С { get; set; }
        public Nullable<decimal> Вес_NpCon { get; set; }
        public Nullable<float> Вес_МДМ { get; set; }
        public Nullable<float> Объём_1С { get; set; }
        public Nullable<decimal> Объём_NPCon { get; set; }
        public Nullable<float> Объём_МДМ { get; set; }
        public Nullable<int> Длина_1С { get; set; }
        public Nullable<int> Длина_NPCon { get; set; }
        public Nullable<short> Длина_МДМ { get; set; }
        public Nullable<int> Высота_1С { get; set; }
        public Nullable<int> Высота_NPCon { get; set; }
        public Nullable<short> Высота_МДМ { get; set; }
        public Nullable<int> Толщина_1С { get; set; }
        public Nullable<int> Толщина_NPCon { get; set; }
        public Nullable<short> Толщина_МДМ { get; set; }
        public Nullable<float> Площадь_1С { get; set; }
        public Nullable<decimal> Площадь_NPCon { get; set; }
        public Nullable<float> Площадь_МДМ { get; set; }
        public Nullable<int> Габ_толщина_1С { get; set; }
        public Nullable<int> Габ_толщина_NPCon { get; set; }
        public Nullable<short> Габ_толщина_МДМ { get; set; }
        public string статус { get; set; }
    }
}
