//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_test_mark07
    {
        public Nullable<int> id_obj { get; set; }
        public string mark { get; set; }
        public Nullable<int> thickness_full { get; set; }
        public string objecttypename { get; set; }
        public string Item_modification_code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Расчётное_значение { get; set; }
        public string created_original_login { get; set; }
        public Nullable<bool> modif_exist { get; set; }
        public string modif_param_value { get; set; }
        public Nullable<int> id_objecttype { get; set; }
        public int id_modif { get; set; }
    }
}
