//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EndPod_TotalDim_2ASPA
    {
        public string Марка { get; set; }
        public string Альбом { get; set; }
        public int C__изделия { get; set; }
        public int изменение { get; set; }
        public int C__версии { get; set; }
        public Nullable<int> C__МДМ { get; set; }
        public string формование { get; set; }
        public string кантователь { get; set; }
        public string статус { get; set; }
        public Nullable<decimal> вес_изделия_т_ { get; set; }
        public Nullable<decimal> вес_металла_кг_ { get; set; }
        public Nullable<decimal> объём { get; set; }
        public Nullable<int> длина { get; set; }
        public Nullable<int> высота { get; set; }
        public Nullable<int> толщина { get; set; }
        public Nullable<int> толщина_габаритная_ { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> макс_дата { get; set; }
    }
}
