//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_РазницаПараметров2
    {
        public string creator_username { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public string Weight { get; set; }
        public Nullable<decimal> NPConWeight { get; set; }
        public string Volume { get; set; }
        public Nullable<decimal> NPConVolume { get; set; }
        public string Length { get; set; }
        public Nullable<int> NPCon_length { get; set; }
        public string Height { get; set; }
        public Nullable<int> NPCon_height { get; set; }
        public string Thickness { get; set; }
        public Nullable<int> NPCon_overall_Thickness { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> NPCon_Area { get; set; }
        public string overall_Thickness { get; set; }
        public Nullable<int> NPCon_thickness { get; set; }
        public string статус { get; set; }
    }
}
