//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_item_const_forming_C1P
    {
        public System.Guid guid { get; set; }
        public string forming_dimension { get; set; }
        public string forming_lifting { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Thickness { get; set; }
        public int Item_construction_id { get; set; }
        public System.Guid Item_construction_guid { get; set; }
    }
}
