//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_elementobjecttype
    {
        public int id_object { get; set; }
        public string unicname { get; set; }
        public bool isproduct { get; set; }
        public string objecttypename { get; set; }
        public Nullable<bool> isendproduct { get; set; }
        public string unicname_trim { get; set; }
        public int id_objecttype { get; set; }
        public Nullable<bool> actual { get; set; }
        public Nullable<int> id_type4mark { get; set; }
        public string typeShortName { get; set; }
    }
}
