//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_1C_mods
    {
        public Nullable<int> id_object_prod { get; set; }
        public decimal ID_MDM { get; set; }
        public string Name { get; set; }
        public string Модификатор { get; set; }
        public Nullable<decimal> Item_modification_ID { get; set; }
        public string Значение { get; set; }
    }
}
