//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_MDM_NpCon_mark_C1P
    {
        public int modification_num { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public string creator_username { get; set; }
        public string blkname { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public int Item_construction_id { get; set; }
        public string created_original_login { get; set; }
    }
}
