//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EndPod_TotalDim
    {
        public int id_endprod_ver { get; set; }
        public string blkname { get; set; }
        public string формование { get; set; }
        public string forming_lifting { get; set; }
        public int изменение { get; set; }
        public string статус { get; set; }
        public Nullable<decimal> вес { get; set; }
        public Nullable<decimal> объём { get; set; }
        public Nullable<int> длина { get; set; }
        public Nullable<int> высота { get; set; }
        public Nullable<int> толщина { get; set; }
        public Nullable<int> толщина_габаритная_ { get; set; }
        public string Альбом { get; set; }
        public int id_object_prod { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.Guid> itm_conFrm_guid { get; set; }
    }
}
