//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_strip
    {
        public Nullable<int> id_normdoc_pobj { get; set; }
        public int id_object { get; set; }
        public int id_objecttype_pobj { get; set; }
        public string unitsguid_pobj { get; set; }
        public bool isagreed { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> agreedate { get; set; }
        public string created_original_login { get; set; }
        public string created_comp_name { get; set; }
        public string created_username { get; set; }
        public string agree_original_login { get; set; }
        public string agree_comp_name { get; set; }
        public string agree_username { get; set; }
        public string unicname { get; set; }
        public string doctype { get; set; }
        public string doccode { get; set; }
        public string description { get; set; }
        public int id_normdoc { get; set; }
        public int id_object_raw { get; set; }
        public decimal weight { get; set; }
        public string weight_units { get; set; }
        public int id_object_strip { get; set; }
        public short width { get; set; }
        public byte thickness { get; set; }
        public string unicname_trim { get; set; }
        public Nullable<bool> actual { get; set; }
    }
}
