//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_WrkFile_MarkPlans
    {
        public int id_object_prod { get; set; }
        public string blkname { get; set; }
        public string unicname_trim { get; set; }
        public string unicname { get; set; }
        public int id { get; set; }
        public System.Guid UUID { get; set; }
        public string f_path { get; set; }
        public string f_Name { get; set; }
        public string f_Extension { get; set; }
        public string Mark { get; set; }
        public string Object { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public System.DateTime Time { get; set; }
        public string Cur_user { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Links { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Parsed { get; set; }
        public string Eml_MailDate { get; set; }
    }
}
