//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewIfcModificator
    {
        public string Name_KZI { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Mass { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Thickness { get; set; }
        public Nullable<bool> Console { get; set; }
        public Nullable<bool> Loop { get; set; }
        public Nullable<bool> Teeth { get; set; }
        public Nullable<bool> TeethPart { get; set; }
        public Nullable<bool> TeethCut { get; set; }
        public Nullable<bool> EndLeft { get; set; }
        public Nullable<bool> EndRight { get; set; }
        public Nullable<bool> Heat { get; set; }
        public Nullable<bool> Window { get; set; }
        public Nullable<bool> Balkony { get; set; }
        public Nullable<bool> Door { get; set; }
        public Nullable<bool> TechCut { get; set; }
        public Nullable<bool> StapleLeft120 { get; set; }
        public Nullable<bool> StapleRight120 { get; set; }
        public Nullable<bool> StapleLeft150 { get; set; }
        public Nullable<bool> StapleRight150 { get; set; }
        public Nullable<bool> StapleLeft245 { get; set; }
        public Nullable<bool> StapleRight245 { get; set; }
        public Nullable<bool> StapleLeft275 { get; set; }
        public Nullable<bool> StapleRIght275 { get; set; }
        public Nullable<bool> StapleTop { get; set; }
        public string RDS { get; set; }
        public string RDS_Light { get; set; }
    }
}
