//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewProjectData
    {
        public System.Guid UID_projects { get; set; }
        public string Name { get; set; }
        public string code { get; set; }
        public System.Guid UID_sections { get; set; }
        public string Name_sections { get; set; }
        public System.Guid UID_floors { get; set; }
        public string Name_floors { get; set; }
        public System.Guid UUID_Work_File { get; set; }
        public string f_Name { get; set; }
        public string f_path { get; set; }
        public string Description { get; set; }
        public System.Guid UID_KZI_Name { get; set; }
        public string Name_KZI { get; set; }
        public string matrix_Insertion { get; set; }
        public string Nomenclature_type { get; set; }
        public string C2d_Plan_KZI { get; set; }
        public string C2d_Fasade_KZI { get; set; }
        public Nullable<System.Guid> UID_Assembly { get; set; }
        public string Assembly_Compare_LISP { get; set; }
        public string Assembly_Parameters_LISP { get; set; }
        public string Name_Color { get; set; }
        public string JSON_Project_Specific { get; set; }
        public Nullable<int> Version_KZI { get; set; }
    }
}
