//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EndProd_Raw
    {
        public string технология_формовки { get; set; }
        public string метод_съёма { get; set; }
        public int изменение { get; set; }
        public string материал_спецификации { get; set; }
        public Nullable<decimal> количество_материала { get; set; }
        public int ID_сырья { get; set; }
        public string единицы_измерения { get; set; }
        public string код_единиц_измерения { get; set; }
        public Nullable<System.DateTime> maxdatecreate { get; set; }
        public Nullable<System.Guid> itm_conFrm_guid { get; set; }
        public string Статус { get; set; }
        public string Альбом { get; set; }
        public string марка { get; set; }
    }
}
