//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_permtype
    {
        public int idmaintype { get; set; }
        public int idpermtype { get; set; }
        public Nullable<bool> isproduct { get; set; }
        public string objecttypename { get; set; }
        public Nullable<bool> isendproduct { get; set; }
        public Nullable<bool> isproductsubobj { get; set; }
        public string objecttypenamesubobj { get; set; }
        public Nullable<bool> isendproductsubobj { get; set; }
        public Nullable<int> id_type4mark { get; set; }
    }
}
