//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Product_Mark_C1P
    {
        public Nullable<int> Product_id { get; set; }
        public string Product { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public string Item_group { get; set; }
        public string Item_group_long { get; set; }
        public int Item_construction_id { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Thickness { get; set; }
        public Nullable<int> Item_group_id { get; set; }
        public Nullable<int> Item_group_long_id { get; set; }
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> item_group_guid { get; set; }
        public Nullable<System.Guid> item_group_long_guid { get; set; }
    }
}
