//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ItmConsID_by_idEndProdVer5
    {
        public Nullable<int> id_endprod_ver { get; set; }
        public Nullable<decimal> end_prod_volume { get; set; }
        public Nullable<decimal> end_prod_weight { get; set; }
        public Nullable<decimal> end_prod_area { get; set; }
        public Nullable<decimal> count_ropes { get; set; }
        public Nullable<int> Item_construction_id { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public string blkname { get; set; }
        public Nullable<int> Item_group_id { get; set; }
        public Nullable<int> prodlength { get; set; }
        public Nullable<int> prodheight { get; set; }
        public Nullable<int> prod_thickness { get; set; }
        public Nullable<int> height_full { get; set; }
        public Nullable<int> length_full { get; set; }
        public Nullable<int> thickness_full { get; set; }
        public int id_object_prod { get; set; }
        public int id_npcon_changes { get; set; }
        public Nullable<bool> id_existance { get; set; }
        public Nullable<int> ConcrVolBtn_IN_ID { get; set; }
        public Nullable<decimal> ConcrVolBtn_IN_vol { get; set; }
        public string ОбъемВнутреннегоСлоя { get; set; }
        public Nullable<int> ConcrVolBtn_ID { get; set; }
        public Nullable<decimal> ConcrVolBtn_vol { get; set; }
        public Nullable<int> ConcrVolBtn_FrontSide_ID { get; set; }
        public Nullable<decimal> ConcrVolBtn_FrontSide_vol { get; set; }
        public Nullable<int> ConcrVolBtn_UpperEndFace_ID { get; set; }
        public Nullable<decimal> ConcrVolBtn_UpperEndFace_vol { get; set; }
        public string ОбъемНаружногоСлоя { get; set; }
        public string ОбъемУтеплителя { get; set; }
        public string ВысотаБезСтупенькиРеновация { get; set; }
        public string ТолщинаНаружногоСлоя { get; set; }
        public string ТолщинаВнутреннегоСлоя { get; set; }
        public string ТолщинаУтеплителя { get; set; }
    }
}
