//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_objalbumorgost
    {
        public int id_object { get; set; }
        public string unicname { get; set; }
        public string name_alb { get; set; }
        public string doctype { get; set; }
        public string doccode { get; set; }
        public string blkname { get; set; }
        public string unicname_trim { get; set; }
        public string listnum { get; set; }
        public Nullable<bool> actual { get; set; }
    }
}
