//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_modificators_oldver
    {
        public Nullable<long> MarkOrd { get; set; }
        public string Марка { get; set; }
        public string Консоль { get; set; }
        public string Выступ_Зуб_ { get; set; }
        public string Утеплитель { get; set; }
        public string Петлевой_выпуск { get; set; }
        public string Торец { get; set; }
        public string Автор { get; set; }
        public string Проем { get; set; }
    }
}
