//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_node
    {
        public Nullable<int> id_normdoc_pobj { get; set; }
        public int id_object { get; set; }
        public int id_objecttype_pobj { get; set; }
        public string unitsguid_pobj { get; set; }
        public bool isagreed { get; set; }
        public System.DateTime createdate { get; set; }
        public Nullable<System.DateTime> agreedate { get; set; }
        public string created_original_login { get; set; }
        public string created_comp_name { get; set; }
        public string created_username { get; set; }
        public string agree_original_login { get; set; }
        public string agree_comp_name { get; set; }
        public string agree_username { get; set; }
        public string unicname { get; set; }
        public Nullable<int> id_album { get; set; }
        public string name_alb { get; set; }
        public string description_alb { get; set; }
        public int id_object_prod { get; set; }
        public Nullable<int> id_album_prod { get; set; }
        public string blkname { get; set; }
        public Nullable<int> prodlength { get; set; }
        public Nullable<int> prodheight { get; set; }
        public int id_objecttype { get; set; }
        public bool isproduct { get; set; }
        public string objecttypename { get; set; }
        public Nullable<bool> isendproduct { get; set; }
        public Nullable<int> id_album_list { get; set; }
        public Nullable<int> id_normdoc { get; set; }
        public string doctype { get; set; }
        public string doccode { get; set; }
        public string description { get; set; }
        public string unitcode { get; set; }
        public string unitname { get; set; }
        public string graphsymbol_rus { get; set; }
        public string unicname_trim { get; set; }
        public string listnum_prod { get; set; }
        public string listnum { get; set; }
        public string file_path { get; set; }
        public Nullable<bool> actual { get; set; }
        public Nullable<int> prod_thickness { get; set; }
        public Nullable<bool> outdoor { get; set; }
        public Nullable<int> id_type4mark { get; set; }
        public string typeShortName { get; set; }
    }
}
