//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_UserActivityStat
    {
        public string UserLogin { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string StartACAD { get; set; }
        public string EndACAD { get; set; }
        public string день_недели { get; set; }
        public string FullTimeWork___ { get; set; }
        public int FullTimeWork { get; set; }
    }
}
