//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_npcon_changed_product_reserve_del
    {
        public int id_npcon_changes { get; set; }
        public Nullable<int> LastVerID_NPCon { get; set; }
        public Nullable<int> ID_MDM { get; set; }
        public string НаименованиеMDM { get; set; }
        public string НаименованиеNPCon { get; set; }
        public Nullable<int> Item_group_id { get; set; }
        public Nullable<int> ГабаритнаяДлина { get; set; }
        public Nullable<int> ГабаритнаяВысота { get; set; }
        public Nullable<int> ГабаритнаяТолщина { get; set; }
        public Nullable<int> Длина { get; set; }
        public Nullable<int> Высота { get; set; }
        public Nullable<int> Толщина { get; set; }
        public Nullable<decimal> Площадь { get; set; }
        public Nullable<decimal> Объем { get; set; }
        public Nullable<decimal> Вес { get; set; }
        public Nullable<decimal> КоличествоКанатов { get; set; }
        public Nullable<int> ВысотаБезСтупенькиРеновация { get; set; }
        public Nullable<int> ID_ВнутреннегоСлоя { get; set; }
        public Nullable<decimal> ОбъемВнутреннегоСлоя { get; set; }
        public Nullable<int> ID_ФасадЧастьОсн { get; set; }
        public Nullable<decimal> ОбъемФасадЧастьОсн { get; set; }
        public Nullable<int> ID_ФасадЧастьБок { get; set; }
        public Nullable<decimal> ОбъемФасадЧастьБок { get; set; }
        public Nullable<int> ID_ТорецВерх_зуб { get; set; }
        public Nullable<decimal> ОбъемТорецВерх_зуб { get; set; }
        public Nullable<double> ОбъемНаружногоСлоя { get; set; }
        public Nullable<double> ОбъемУтеплителя { get; set; }
        public Nullable<int> ТолщинаВнутреннегоСлоя { get; set; }
        public Nullable<int> ТолщинаНаружногоСлоя { get; set; }
        public Nullable<int> ТолщинаУтеплителя { get; set; }
        public int ID_NPCon { get; set; }
        public Nullable<bool> id_existance { get; set; }
    }
}
