//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_endproduct
    {
        public Nullable<int> id_normdoc_pobj { get; set; }
        public Nullable<int> id_object { get; set; }
        public Nullable<int> id_objecttype_pobj { get; set; }
        public string unitsguid_pobj { get; set; }
        public Nullable<bool> isagreed { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> agreedate { get; set; }
        public string created_original_login { get; set; }
        public string created_comp_name { get; set; }
        public string created_username { get; set; }
        public string agree_original_login { get; set; }
        public string agree_comp_name { get; set; }
        public string agree_username { get; set; }
        public string unicname { get; set; }
        public string name_alb { get; set; }
        public string description_alb { get; set; }
        public Nullable<int> id_object_prod { get; set; }
        public Nullable<int> id_album_prod { get; set; }
        public string blkname { get; set; }
        public Nullable<int> prodlength { get; set; }
        public Nullable<int> prodheight { get; set; }
        public Nullable<int> id_objecttype { get; set; }
        public Nullable<bool> isproduct { get; set; }
        public string objecttypename { get; set; }
        public Nullable<bool> isendproduct { get; set; }
        public string unicname_trim { get; set; }
        public string listnum_prod { get; set; }
        public string file_path { get; set; }
        public Nullable<bool> actual { get; set; }
        public Nullable<int> prod_thickness { get; set; }
        public Nullable<bool> outdoor { get; set; }
        public Nullable<int> id_type4mark { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string unitname { get; set; }
        public int id_endprod_ver { get; set; }
        public int id_end_prod { get; set; }
        public int modification_num { get; set; }
        public string modification_descr { get; set; }
        public System.DateTime created_at { get; set; }
        public string creator_username { get; set; }
        public bool eprod_actual { get; set; }
        public int ver_status { get; set; }
        public Nullable<int> execution_ver { get; set; }
        public int id_eprod_album { get; set; }
        public Nullable<System.Guid> itm_conFrm_guid { get; set; }
        public string eprod_file_path { get; set; }
        public Nullable<System.Guid> objtypguid { get; set; }
        public string status_name { get; set; }
        public string forming_dimension { get; set; }
        public string forming_lifting { get; set; }
        public string Hand_mark_no_colour { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Thickness { get; set; }
        public Nullable<int> length_full { get; set; }
        public Nullable<int> height_full { get; set; }
        public Nullable<int> thickness_full { get; set; }
        public Nullable<decimal> end_prod_weight { get; set; }
        public Nullable<decimal> end_prod_volume { get; set; }
        public Nullable<int> id_workfile { get; set; }
        public Nullable<bool> in_design { get; set; }
        public string frm_dimension { get; set; }
        public string frm_lifting { get; set; }
        public Nullable<System.Guid> formin_type_guid { get; set; }
        public Nullable<decimal> end_prod_area { get; set; }
        public Nullable<int> Item_construction_id { get; set; }
        public Nullable<int> id_mdm { get; set; }
        public string nrm_unicname_trim { get; set; }
        public Nullable<bool> renovation { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<bool> buying_part { get; set; }
        public Nullable<int> rotate_layers { get; set; }
        public Nullable<decimal> prod_weight { get; set; }
    }
}
