//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WINDOWS_DOORS_to_1C
    {
        public Nullable<int> id_mdm { get; set; }
        public int id_proem { get; set; }
        public Nullable<int> t_a { get; set; }
        public int actual { get; set; }
        public string mark { get; set; }
        public string aperture_geomerty { get; set; }
        public string type_of_aperture { get; set; }
        public System.Guid UUID { get; set; }
        public System.DateTime created_by { get; set; }
        public Nullable<System.DateTime> moved_to_1c { get; set; }
        public string Responsible_person { get; set; }
    }
}
