//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public work_file()
        {
            this.prod_work_file = new HashSet<prod_work_file>();
            this.KZIs = new HashSet<KZI>();
            this.work_file_mark_type = new HashSet<work_file_mark_type>();
            this.work_file1 = new HashSet<work_file>();
            this.mdm_object_plain = new HashSet<mdm_object_plain>();
            this.zones = new HashSet<zone>();
        }
    
        public int id { get; set; }
        public System.Guid UUID { get; set; }
        public string f_path { get; set; }
        public string f_Name { get; set; }
        public string f_Extension { get; set; }
        public string Mark { get; set; }
        public string Object { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public System.DateTime Time { get; set; }
        public string Cur_user { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Links { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Parsed { get; set; }
        public string MailDate { get; set; }
        public Nullable<int> Project_id { get; set; }
        public Nullable<int> Korpus_id { get; set; }
        public Nullable<int> Section_id { get; set; }
        public string original_login { get; set; }
        public Nullable<System.DateTime> loaded_date { get; set; }
        public Nullable<int> @class { get; set; }
    
        public virtual classType classType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prod_work_file> prod_work_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KZI> KZIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_file_mark_type> work_file_mark_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_file> work_file1 { get; set; }
        public virtual work_file work_file2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mdm_object_plain> mdm_object_plain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zone> zones { get; set; }
    }
}
