//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAKL_ANKERA_all_comp
    {
        public string Наим__изделия__вар_1_ { get; set; }
        public string Наим__изделия__вар_2_ { get; set; }
        public string Закладная { get; set; }
        public Nullable<int> Кол_во_закладных_в_КЖИ { get; set; }
        public string Марка_составляющей { get; set; }
        public string Вид_составляющей { get; set; }
        public Nullable<decimal> Измеритель_составляющей { get; set; }
        public string Ед__измерения { get; set; }
        public Nullable<int> Кол_во_составляющих_в_закладной { get; set; }
        public Nullable<int> Кол_во_составляющих_в_изделии { get; set; }
    }
}
