//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ГабаритыNPCon
    {
        public string Пользователь { get; set; }
        public string Марка { get; set; }
        public Nullable<int> C1С_Вес { get; set; }
        public Nullable<int> Аспецифик_вес { get; set; }
        public Nullable<decimal> C1С_объем { get; set; }
        public Nullable<decimal> Аспецифик_Объём { get; set; }
        public Nullable<int> C1С_Длина { get; set; }
        public Nullable<int> Аспецифик_длина { get; set; }
        public Nullable<int> C1С_высота { get; set; }
        public Nullable<int> Аспецифик_высота { get; set; }
        public Nullable<int> C1С_толщина { get; set; }
        public Nullable<int> Аспецифик_толщина { get; set; }
        public Nullable<decimal> Площадь { get; set; }
        public Nullable<decimal> Аспецифик_площадь { get; set; }
        public Nullable<int> C1С_габар_толщина { get; set; }
        public Nullable<int> Аспецифик_габар_толщина { get; set; }
        public string статус { get; set; }
    }
}
