//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASpecWpfDbFirstTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class РолиУКРна_05_06_2019
    {
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public string LoginName { get; set; }
        public string DbName { get; set; }
        public string SchemaName { get; set; }
        public int UserID { get; set; }
    }
}
